### ISSUE TITLE
Swap B-A only

### ISSUE THREAD

**Issue by L0czki** [stunndard/Nintendo_Switch_Button_Remap#2]
Hey,

would you be able to create a mod which swaps only B-A buttons?

Or maybe share your source code so I could do it on my own? :)

Thanks!

**Comment by SiilentSaiint** [comment]
Hey, I'd also like a A/B swap but also a R/ZR swap. It's the only way I can play Tears of the Kindom. I'd also like the source code to do it on my own aswell. 

Thanks for the great work no one else is doing.

**Comment by Zot1881** [comment]
Same, can you add version to swap only a and b? Thank you.

**Comment by xlopets1337** [comment]
I vehemently support the request for a mod to reassign only the a/b buttons
I am ready to donate

**Comment by stunndard** [comment]
Will do swapping A-B only as a separate patch soon

**Comment by stunndard** [comment]
Added A-B only swap.
