### ISSUE TITLE
Update for new firmware if possible, Swap B-A only

### ISSUE THREAD

**Issue by xMounirV** [stunndard/Nintendo_Switch_Button_Remap#4]
Hello :) ,

I'm humbly asking if you'd be able to make an update for Firmware 17.0.0 
and is it possible to swap only B-A buttons.

I'm certain a lot of people are ready to donate or buy this patch including me.

Thanks in advance !

**Comment by xlopets1337** [comment]
Dear stunndard, I support the request of the user with the nickname xMounirV
We really need this mod

**Comment by Kyruzh** [comment]
Would love to have this on my 17.00 switch

**Comment by stunndard** [comment]
updated for 17.0.x

**Comment by xMounirV** [comment]
Thank you so much, I will not update my switch to keep this working,
It will be great to swap A and B only, but this is also useful , Thanx for your efforts
