### ISSUE TITLE
My Nintendo Switch Lite didn't recognize the files of this patch

### ISSUE THREAD

**Issue by teysuzin** [stunndard/Nintendo_Switch_Button_Remap#8]
I put the files on my Nintendo Switch Lite, but the settings didn't work, and the A and B buttons weren't swapped.

**Comment by stunndard** [comment]
This is for controllers that connect to the Switch/Switch OLED joycon rail. Switch Lite buttons can be remapped using the stock OS. It doesn't have joycon rail.
